android/src/main/kotlin/top/kikt/imagescanner/ImageScanner.kt
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/thumb/ThumbnailUtil.kt
example/lib/photo_list.dart
ios/Classes/ImageScanner.h
ios/Classes/ImageScanner.m
ios/Classes/ImageScannerPlugin.m
ios/Classes/PHAsset+PHAsset_checkType.h
ios/Classes/PHAsset+PHAsset_checkType.m
lib/photo_manager.dart

add the video in android
and ImageEntity add a `type` with asset path.

Video Scan api

---

CHANGELOG.md
README.md
ios/Classes/ImageScanner.m

async create video file

---

CHANGELOG.md
README.md
lib/photo_manager.dart
pubspec.yaml

fix all path hasVideo property bug

---

CHANGELOG.md
README.md
lib/photo_manager.dart
pubspec.yaml

fix bug and update version

---

CHANGELOG.md
README.md
android/src/main/kotlin/top/kikt/imagescanner/ImageScanner.kt
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/lib/main.dart
lib/photo_manager.dart
pubspec.yaml

0.1.7 fix android's latest picture won't be found

---

android/src/main/kotlin/top/kikt/imagescanner/ImageScanner.kt

don't crash in ImageScanner if img is null

---

CHANGELOG.md
README.md
android/src/main/kotlin/top/kikt/imagescanner/ImageScanner.kt
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
ios/Classes/ImageScanner.m
lib/src/factory.dart
lib/src/manager.dart
pubspec.yaml

Get cached assetPathList

---

android/.project
android/.settings/org.eclipse.buildship.core.prefs
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/RefreshObserver.kt
example/lib/main.dart
ios/Classes/ImageScanner.h
ios/Classes/ImageScanner.m
ios/Classes/ImageScannerPlugin.m
ios/PhotoChangeObserver.h
ios/PhotoChangeObserver.m
lib/photo_manager.dart
lib/src/manager.dart
lib/src/notify.dart

Observer on photo change

---

CHANGELOG.md
android/src/main/kotlin/top/kikt/imagescanner/ImageScanner.kt
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
example/lib/main.dart
example/lib/photo_list.dart
ios/Classes/ImageScanner.h
ios/Classes/ImageScanner.m
ios/Classes/ImageScannerPlugin.m
lib/src/entity.dart
lib/src/manager.dart
lib/src/notify.dart

add field createTime for AssetEntity

---

CHANGELOG.md
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
ios/Classes/ImageScanner.m
lib/src/entity.dart
lib/src/manager.dart
pubspec.yaml

close #58 
Because Flutter's Image does not support HDR, it needs to be addressed in other ways.

update origin file for iOS

---

ios/Classes/ImageScanner.m

update for collection type

---

README.md

corrected video duration property name to videoDuration

fixed property name and initialized data variable in readme

---

ios/Classes/ImageScanner.m

I got the same crash as #60 but in a different call. It is unclear to me how to reproduce the issue as it has something to do with what albums the phone has on it. The phone that was crashing has many many albums, one of which must have been causing the issue.

another fix for crash of same cause as #60

---

android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/ImageScanner.kt
android/src/main/kotlin/top/kikt/imagescanner/core/ResultHandler.kt
android/src/main/kotlin/top/kikt/imagescanner/core/permission/PermissionsListener.java
android/src/main/kotlin/top/kikt/imagescanner/core/permission/PermissionsUtils.java
android/src/main/kotlin/top/kikt/imagescanner/core/refresh/Refresh.kt
android/src/main/kotlin/top/kikt/imagescanner/core/refresh/RefreshObserver.kt
android/src/main/kotlin/top/kikt/imagescanner/core/thumb/CustomTarget.java
android/src/main/kotlin/top/kikt/imagescanner/core/thumb/ThumbnailUtil.kt

- Refactoring the android code structure.
- Removed references to Fragment obsolete.

Clean up android code.

---

example/ios/Podfile.lock
ios/Classes/core/ConvertUtils.h
ios/Classes/core/PMPlugin.m

import library.
wrap BOOL with @.

Fix ios build error

---

ios/Classes/core/PMManager.m

This pull request removes some deprecated iOS api usages, saves the downloaded image into a temp file and returns the path to flutter plugin.
Let me know if you need help to improve iOS code like converting it to Swift.

Fix get image full size on iOS

---

README.md
android/build.gradle
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/ConvertUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
example/ios/Flutter/flutter_export_environment.sh
example/ios/Podfile.lock
example/lib/model/photo_provider.dart
example/lib/page/gallery_list_page.dart
example/lib/page/image_list_page.dart
ios/Classes/core/ConvertUtils.h
ios/Classes/core/ConvertUtils.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
ios/Classes/core/PMPlugin.m
lib/photo_manager.dart
lib/src/editor.dart
lib/src/manager.dart
lib/src/plugin.dart
lib/src/utils/convert_utils.dart

Save image and video

---

CHANGELOG.md
README.md
android/src/main/kotlin/top/kikt/imagescanner/core/entity/AssetEntity.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/ConvertUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
example/ios/Podfile.lock
example/lib/page/detail_page.dart
example/lib/page/image_list_page.dart
ios/Classes/core/ConvertUtils.m
ios/Classes/core/PMAssetPathEntity.h
ios/Classes/core/PMManager.m
lib/src/entity.dart
lib/src/utils/convert_utils.dart

Add modified date property for AssetEntity.
Update example.
Fix create date.

Add modified date property for AssetEntity.

---

ios/Classes/core/PMManager.m

#132 Showing all `Smart Albums` such as 'Favorites', 'Recently Added'.

Change ios gallery subtype. 

---

example/.flutter-plugins-dependencies
example/ios/Flutter/Flutter.podspec
example/ios/Podfile.lock
example/lib/main.dart
example/lib/page/image_list_page.dart
example/lib/page/index_page.dart
example/lib/page/save_image_example.dart
ios/Classes/core/PMManager.m

Fix save image on ios.

---

android/src/main/kotlin/top/kikt/imagescanner/core/entity/AssetEntity.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/ConvertUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
example/lib/page/detail_page.dart
ios/Classes/core/ConvertUtils.m
ios/Classes/core/PHAsset+PHAsset_getTitle.h
ios/Classes/core/PHAsset+PHAsset_getTitle.m
ios/Classes/core/PMAssetPathEntity.h
ios/Classes/core/PMManager.m
lib/src/entity.dart
lib/src/utils/convert_utils.dart

Add title property for AssetEntity.

---

example/lib/page/image_list_page.dart
ios/Classes/core/PMManager.m

Rename origin file cache name.

---

android/.settings/org.eclipse.buildship.core.prefs
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/cache/AndroidQCache.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
example/lib/page/image_list_page.dart
example/lib/widget/dialog/list_dialog.dart
lib/src/entity.dart
lib/src/manager.dart
lib/src/plugin.dart

Resolved #159 ,resolved #151, resolved #119.

Implement originBytes.

---

android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/old/ImageScanner.kt
android/src/main/kotlin/top/kikt/imagescanner/thumb/ThumbnailUtil.kt
android/src/main/kotlin/top/kikt/imagescanner/util/ResultHandler.kt
example/lib/page/image_list_page.dart
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
ios/Classes/core/PMPlugin.m
lib/src/entity.dart
lib/src/manager.dart
lib/src/plugin.dart
lib/src/type.dart

Add format for thumb

---

example/ios/Podfile.lock
example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
ios/Classes/core/PHAsset+PHAsset_getTitle.m

Fix title error for iOS.

---

.gitignore
android/.settings/org.eclipse.buildship.core.prefs
android/src/main/AndroidManifest.xml
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/old/permission/PermissionsListener.java
android/src/main/kotlin/top/kikt/imagescanner/old/permission/PermissionsUtils.java
lib/src/entity.dart
lib/src/plugin.dart

Fix error of location permission for androidQ.

---

android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt

Update gallery name to nullable.

---

android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt

The getThumb method will be called in background thread in Android.

---

ios/Classes/core/PMPlugin.m
ios/Classes/core/ResultHandler.m

Run code in background thread on iOS.

---

android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt

Fix exists in android.

---

README.md

This PR needs to have my PR to your project some_assets approved first to display new assets.

updated ios readme to support localized system album names

---

android/src/main/kotlin/top/kikt/imagescanner/util/ResultHandler.kt

Already submit result don't repeat.

---

CHANGELOG.md
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/entity/FilterOption.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/ConvertUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/RequestTypeUtils.kt
example/ios/Podfile.lock
example/lib/model/photo_provider.dart
example/lib/page/detail_page.dart
example/lib/page/home_page.dart
example/lib/widget/image_item_widget.dart
example/lib/widget/video_widget.dart
ios/Classes/PHAsset+PHAsset_checkType.h
ios/Classes/core/ConvertUtils.m
ios/Classes/core/NSString+PM_COMMON.h
ios/Classes/core/NSString+PM_COMMON.m
ios/Classes/core/PMFilterOption.h
ios/Classes/core/PMManager.m
ios/Classes/core/PMRequestTypeUtils.h
ios/Classes/core/PMRequestTypeUtils.m
lib/src/entity.dart
lib/src/filter/filter_options.dart
lib/src/manager.dart
lib/src/plugin.dart
lib/src/type.dart

Only support android.
Although the PHLibrary library contains audio type and api, but no audio resource in photos.
Save audio resource to PHLibrary always fail.

Add audio type

---

README.md

Documentation is not properly updated right now, seems we need to change filteroption by a FilterOptionGroup that would include different kind of options per asset Type ?

Fix URL link

---

CHANGELOG.md
README.md
example/lib/page/developer/develop_index_page.dart
example/lib/page/developer/ios/create_folder_example.dart
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
ios/Classes/core/PMPlugin.m
lib/src/editor.dart
lib/src/plugin.dart

Create folder ios

---

CHANGELOG.md
README.md
example/lib/widget/gallery_item_widget.dart
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
ios/Classes/core/PMPlugin.m
lib/src/editor.dart
lib/src/plugin.dart

Delete album or folder.

---

CHANGELOG.md
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
example/lib/page/detail_page.dart
lib/src/entity.dart
pubspec.yaml

Update android change media url from file scheme to content scheme.

Change media url

---

android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt

Fix  asset count of api 28

---

example/lib/page/copy_to_another_gallery_example.dart
example/lib/page/image_list_page.dart
example/lib/page/move_to_another_gallery_example.dart
example/lib/photo_list.dart
example/lib/widget/image_item_widget.dart
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
ios/Classes/core/PMPlugin.m
lib/photo_manager.dart
lib/src/entity.dart
lib/src/filter/load_option.dart
lib/src/manager.dart
lib/src/plugin.dart
lib/src/type.dart
macos/Classes/core/PMManager.h
macos/Classes/core/PMManager.m
macos/Classes/core/PMPlugin.m

**New thumb image load options for iOS**
#318

[PR] Load image options

---

lib/src/filter/filter_options.dart

* Provide merging ability to the `FilterOption` using `copyWith` .
* Add `getOption` to `FilterOptionGroup` .

Add copyWith to FilterOption

---

CHANGELOG.md
lib/src/filter/filter_options.dart
pubspec.yaml

* Add `merge` to `FilterOption` and `FilterOptionGroup` .
* Bumping version to 0.5.5
Related issue: https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/41

Add `merge` to `FilterOption` and `FilterOptionGroup`

---

android/src/main/kotlin/top/kikt/imagescanner/core/entity/AssetEntity.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt

fix save path

---

ios/Classes/core/PMPlugin.m

FIX #319 [BUG] Crash on iOS create album

---

example/pubspec.yaml
ios/Classes/core/PMPlugin.m

Related #319, fix create folder error.
Modifying the plugin native log no longer requires album permission.

Fix some error

---

android/src/main/kotlin/top/kikt/imagescanner/core/cache/AndroidQCache.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt

Fix error for androidQ cache with audio type.

---

CHANGELOG.md
Migration-Guide.md
README.md
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/entity/FilterOption.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/Android30DbUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/ConvertUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/IDBUtils.kt
example/android/app/src/main/AndroidManifest.xml
example/lib/model/photo_provider.dart
example/lib/page/image_list_page.dart
ios/Classes/core/ConvertUtils.m
ios/Classes/core/PMConvertUtils.h
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMFilterOption.h
ios/Classes/core/PMFilterOption.m
ios/Classes/core/PMManager.m
ios/Classes/core/PMNotificationManager.m
ios/Classes/core/PMPlugin.m
lib/src/entity.dart
lib/src/filter/filter_options.dart
lib/src/manager.dart
lib/src/plugin.dart
pubspec.yaml

Update date condition filter.

---

CHANGELOG.md
android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerDeleteManager.kt
android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
lib/src/filter/filter_options.dart
pubspec.yaml

0.6.0 patch 1

---

ios/Classes/core/PHAsset+PHAsset_getTitle.h
ios/Classes/core/PHAsset+PHAsset_getTitle.m
ios/Classes/core/PMManager.m

Fix edited data

---

android/src/main/kotlin/top/kikt/imagescanner/util/ResultHandler.kt

Safeguard against "Reply already submitted" crashes

---

CHANGELOG.md
lib/src/entity.dart
lib/src/utils/convert_utils.dart
pubspec.yaml

Improve asset entity's constructor for null safety

---

android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt

Fix was very simple i jus returned  `resultHandler.reply(ids)` instad of  `resultHandler.reply(true)`
Thank you !

'bool' is not a subtype of type 'List<dynamic>' in type cast issue fix.

---

android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
lib/src/plugin.dart

First, thank you. This package that you developed helps for me.
I've been using this for long time but there has a bug that cannot work of setCacheOriginBytes.
It occurs an exception when calls it.
I fixed and using for myself before but I thought it's better to share this for everyone including you even if it's simple
Thank you

fix to set cacheOriginBytes

---

android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt

Handle errors in deleteWithIds gracefully

---

android/src/main/kotlin/top/kikt/imagescanner/permission/PermissionsUtils.java
ios/Classes/PMPlugin.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m

Fix `openSettings` method

---

ios/Classes/PMPlugin.m

The `setLog` does not take effect in IOS. The PR will fix it.

Fix log error of iOS

---

example/macos/Podfile.lock
ios/Classes/PMPlugin.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m

Some  compatibility of macOS

---

android/src/main/kotlin/top/kikt/imagescanner/core/PhotoManagerPlugin.kt
android/src/main/kotlin/top/kikt/imagescanner/permission/PermissionsUtils.java

Prevent multiple permission requests on Android

---

ios/Classes/core/PMManager.m

Applying fixes from https://github.com/CaiJingLong/flutter_photo_manager/commit/39d6c6a288148aed68f2ec4bbbd2a891a9b68214 and https://github.com/CaiJingLong/flutter_photo_manager/commit/c9845ed4c990dc0ff6303b7c3469807754414e7e .
Seems to be a potential fix to #308, #377, #411, #420.

Reply result after the export session is completed

---

ios/Classes/core/PMAssetPathEntity.h
ios/Classes/core/PMConvertUtils.h
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMManager.m
lib/src/entity.dart
lib/src/utils/convert_utils.dart

This is an implementation from the answer: https://stackoverflow.com/a/46389950/13235500 .
On Android, it'll always be `true`.

Ability to check whether the asset is locally available on iOS

---

lib/src/filter/filter_options.dart

Fixes https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/180 .

Fix `FilterOptionGroup.merge` not merging all fields

---

ios/Classes/PMPlugin.m
ios/Classes/core/PMConvertUtils.h
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/entity.dart
lib/src/manager.dart
lib/src/plugin.dart
lib/src/utils/convert_utils.dart

Fixes #567 . /cc @jaysignorello

♻️ Make `isLocallyAvailable` as a Future getter

---

ios/Classes/core/PMManager.m

Fixes #388 .
This makes the `getMediaUrl` method behaves the same between videos, but the regression is that slow motion video will be played in the original speed since they are composited with extra encoders.

⚡️ Improve `getMediaUrl` method behaviors

---

lib/src/entity.dart

Provide getters that would follow the orientation to match a humanic understanding of width and height.

✨ Add orientated getters

---

CHANGELOG.md
example/lib/main.dart
example/lib/model/photo_provider.dart
example/lib/page/copy_to_another_gallery_example.dart
example/lib/page/detail_page.dart
example/lib/page/developer/create_entity_by_id.dart
example/lib/page/developer/develop_index_page.dart
example/lib/page/filter_option_page.dart
example/lib/page/gallery_list_page.dart
example/lib/page/home_page.dart
example/lib/page/image_list_page.dart
example/lib/page/index_page.dart
example/lib/page/sub_gallery_page.dart
example/lib/widget/gallery_item_widget.dart
example/lib/widget/image_item_widget.dart
example/pubspec.yaml
lib/src/entity.dart
pubspec.yaml

Loosen comparison between `AssetEntity`s

---

ios/Classes/core/PMManager.m

Prettify file name on iOS

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/entity/ThumbLoadOption.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/thumb/ThumbnailUtil.kt
example/ios/Runner/Info.plist
lib/src/types/thumb_option.dart

⚡️ Obtain the first frame for the video thumbnail

---

ios/Classes/core/PMManager.m

⚡️ Load edited videos on iOS

---

ios/Classes/core/PHAsset+PHAsset_getTitle.m
ios/Classes/core/PMManager.m

⚡️ Load edited images on iOS

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt
ios/Classes/PMPlugin.m
ios/Classes/core/PMManager.m
lib/src/internal/plugin.dart
lib/src/managers/photo_manager.dart
lib/src/utils/convert_utils.dart

🔥 Destruct data map for some channel methods

---

ios/Classes/core/PMAssetPathEntity.h
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMManager.m
lib/src/types/entity.dart
lib/src/utils/convert_utils.dart

By adding this support:
- The plugin also supports obtaining the media URL from *Live Photos*.
- `_isLivePhoto` getter is available for `AssetEntity`.

✨ Add subtype support

---

lib/src/internal/plugin.dart
lib/src/managers/photo_manager.dart
lib/src/utils/convert_utils.dart

🚀 Fallback to the given title when saving entities

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/Android30DbUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt

⚡️ Obtain `DATE_TAKEN` if possible on Android

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/entity/FilterOption.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMFilterOption.h
ios/Classes/core/PMFilterOption.m
lib/src/filter/filter_options.dart

Resolves #646.
This will allow retrieving assets with NULL duration.

✨ `DurationConstraint.allowNullable`

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/Android30DbUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt

⚡️ Retrieve width/height from ExifInterface for fallback

---

lib/photo_manager.dart
lib/src/internal/plugin.dart
lib/src/managers/photo_manager.dart
test/photo_manager_test.dart

🚀 Allow plugin to be customized/mocked with tests

---

example/lib/widget/video_widget.dart
ios/Classes/core/PMFileHelper.h
ios/Classes/core/PMFileHelper.m
ios/Classes/core/PMManager.m

⚡️ [iOS] Improve video export when using `file` getter

---

README.md
example/lib/main.dart
example/lib/model/photo_provider.dart
example/lib/page/copy_to_another_gallery_example.dart
example/lib/page/detail_page.dart
example/lib/page/home_page.dart
example/lib/page/image_list_page.dart
example/lib/page/move_to_another_gallery_example.dart
example/lib/widget/image_item_widget.dart
example/lib/widget/live_photos_widget.dart
lib/photo_manager.dart
lib/src/internal/constants.dart
lib/src/internal/enums.dart
lib/src/internal/image_provider.dart
lib/src/internal/plugin.dart
lib/src/managers/caching_manager.dart
lib/src/types/entity.dart
lib/src/types/thumbnail.dart

- Add `AssetEntityImage`
- Add `ThumbnailSize`
Breaking changes:
- `ThumbFormat` -> `ThumbnailFormat`
- `ThumbOption` -> `ThumbnailOption`

⚡️ Improve the image provider

---

android/src/main/kotlin/com/fluttercandies/photo_manager/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
ios/Classes/PMPlugin.m
ios/Classes/core/PHAssetCollection+PHAssetCollection_obtainAssetCount.h
ios/Classes/core/PHAssetCollection+PHAssetCollection_obtainAssetCount.m
ios/Classes/core/PMManager.m

⚡️ Improve path modified injection

---

android/src/main/kotlin/com/fluttercandies/photo_manager/PhotoManagerPlugin.kt

Release reference of Activity on PhotoManagerPlugin detached from Activity

Fix activity leaks on Android

---

ios/Classes/core/PMManager.m
lib/src/types/entity.dart

Allow the `PMProgressHandler` integrates with subtype loading.

🚀 Expand `withSubtype` for `loadFile`

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt

🚑️ [Android] Ensure file exists before reading EXIF

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt

⚡️ [Android] Read orientation when saving images

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt

🚨 [Android] Improve generic type casts on Android

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/CommonExt.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt

🚑️ [Android] Fix invalid `InputStream` when saving images

---

example/lib/model/photo_provider.dart

The pull request will fix an error of load more in example.

Fix an error of example load more

---

CHANGELOG.md
ios/Classes/PMPlugin.m
ios/Classes/core/PHAsset+PM_COMMON.h
ios/Classes/core/PHAsset+PM_COMMON.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/internal/plugin.dart
lib/src/types/entity.dart
pubspec.yaml

Modify the titleAsync implementation on iOS.

---

ios/Classes/core/PHAsset+PM_COMMON.h

Modify the reference method of PMLogUtils.h

---

CHANGELOG.md
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
pubspec.yaml

Fix ios clear cache

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/CommonExt.kt
example/lib/page/developer/develop_index_page.dart
example/lib/page/developer/issues_page/issue_734.dart
example/lib/page/developer/issues_page/issue_index_page.dart

Fix asset not found in android 29+

---

CHANGELOG.md
analysis_options.yaml
example/lib/main.dart
example/lib/page/change_notify_page.dart
example/lib/page/copy_to_another_gallery_example.dart
example/lib/page/detail_page.dart
example/lib/page/developer/create_entity_by_id.dart
example/lib/page/developer/dev_title_page.dart
example/lib/page/developer/develop_index_page.dart
example/lib/page/developer/ios/create_folder_example.dart
example/lib/page/developer/ios/edit_asset.dart
example/lib/page/developer/remove_all_android_not_exists_example.dart
example/lib/page/filter_option_page.dart
example/lib/page/gallery_list_page.dart
example/lib/page/home_page.dart
example/lib/page/image_list_page.dart
example/lib/page/index_page.dart
example/lib/page/move_to_another_gallery_example.dart
example/lib/page/save_image_example.dart
example/lib/page/sub_gallery_page.dart
example/lib/util/log.dart
example/lib/widget/change_notifier_builder.dart
example/lib/widget/dialog/duration_picker.dart
example/lib/widget/dialog/list_dialog.dart
example/lib/widget/live_photos_widget.dart
example/lib/widget/video_widget.dart
example/pubspec.yaml
lib/src/internal/image_provider.dart
lib/src/types/thumbnail.dart
pubspec.yaml

Compatible between Flutter 2 and 3.

🚀 Loosen version constraint

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt
example/pubspec.yaml
pubspec.yaml

🚑️ [Android] Protect cursors convert

---

CHANGELOG.md
lib/src/internal/plugin.dart
lib/src/managers/photo_manager.dart
lib/src/types/types.dart
pubspec.yaml

✏️ Correct `PermissionRequestOption` with a class type alias

---

example/lib/page/image_list_page.dart
ios/Classes/core/PMManager.m

⚡️ [iOS] Check `canPerformEditOperation` before performing change requests

---

CHANGELOG.md
example/lib/page/home_page.dart
ios/Classes/PMNotificationManager.m
lib/src/internal/plugin.dart
lib/src/managers/notify_manager.dart
lib/src/managers/photo_manager.dart
pubspec.yaml

⚡️ Improve change notify

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
ios/Classes/PMPlugin.m
pubspec.yaml

🐛 Fix not replied method calls

---

CHANGELOG.md
ios/Classes/core/PMCacheContainer.m

⚡️ [iOS] Improve cache container mutations

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt
pubspec.yaml

Fix #825 #826, continue with #815.

🐛 [Android] Ignore the existence when saving video with path

---

CHANGELOG.md
README.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/cache/ScopedCache.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/CommonExt.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/util/LogUtils.kt
example/android/app/src/main/AndroidManifest.xml
example/lib/page/detail_page.dart
example/lib/page/image_list_page.dart
example/lib/widget/image_item_widget.dart
example/lib/widget/video_widget.dart
example/pubspec.yaml
pubspec.yaml

✨ Fully support scoped storage

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/thumb/ThumbnailUtil.kt
example/pubspec.yaml
pubspec.yaml

⚡️ [Android] Use `AssetEntity.modifiedDate` for Glide cache key

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionsUtils.kt
example/pubspec.yaml
pubspec.yaml

🐛 [Android] Fix pending permissions request on Android

---

example/lib/main.dart
example/lib/model/photo_provider.dart
example/lib/page/developer/create_entity_by_id.dart
example/lib/page/developer/dev_title_page.dart
example/lib/page/developer/develop_index_page.dart
example/lib/page/developer/ios/create_folder_example.dart
example/lib/page/developer/remove_all_android_not_exists_example.dart
example/lib/page/home_page.dart
example/lib/page/image_list_page.dart
example/lib/page/index_page.dart
example/lib/page/save_image_example.dart
example/lib/widget/dialog/list_dialog.dart

* Add padding for most page
* fix recycle loading at image_list_page when there's invalid media entity

Improve example

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/entity/filter/CommonFilterOption.kt
example/lib/page/developer/issues_page/issue_734.dart
example/lib/page/developer/issues_page/issue_918.dart
example/lib/page/developer/issues_page/issue_index_page.dart
example/lib/page/home_page.dart
example/lib/widget/nav_column.dart
example/lib/widget/theme_button.dart
example/pubspec.yaml

🐛 [Android] Fix filter option group

---

pubspec.yaml

Upgrade version to 2.7.1

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt

[Android] Correct the key when fetching video info with MMR

---

README-ZH.md
README.md

docs: Update README for kotlin version

---

lib/src/types/entity.dart

style: format code for scores of pub.dev

---

example/android/build.gradle

- The `flutter build apk` auto change method

chore: gradle file for example

---

android/build.gradle
example/android/gradle.properties

build: Update gradle log and example's gradle version

---

example/lib/page/developer/issues_page/issue_index_page.dart
example/lib/widget/nav_column.dart

chore: Update an example page title and button title

---

example/lib/page/developer/issues_page/issue_988.dart
example/lib/page/developer/issues_page/issue_index_page.dart

chore: add example for issue 988

---

README-ZH.md
README.md

docs: Update README for ImageProvider

---

CHANGELOG.md
ios/Classes/PMNotificationManager.m
ios/Classes/PMProgressHandler.m
pubspec.yaml

fix[darwin]: dispatch channel in main thread

---

CHANGELOG.md
lib/src/types/entity.dart
pubspec.yaml

🔥 Remove the restriction of `getMediaUrl`

---

CHANGELOG.md
example/pubspec.yaml
ios/Classes/core/PHAsset+PM_COMMON.m
pubspec.yaml

🚸 Do not predicate subtypes images as adjusted

---

.github/workflows/build-example-apk.yml
.github/workflows/check-compatibility.yml
.github/workflows/runnable.yml
CHANGELOG.md
lib/src/filter/custom/advance.dart
lib/src/filter/path_filter.dart

CI: Action - Code Analysis

---

example/lib/page/custom_filter/custom_filter_sql_gif_image.dart
example/lib/page/custom_filter_example_page.dart
lib/src/filter/custom/custom_columns.dart

Utilize this tool to enhance iOS filtering capabilities for images and videos, including support for GIFs.
docs: [playbackstyle](https://developer.apple.com/documentation/photokit/phasset/2909060-playbackstyle)

Add field playbackStyle to DarwinColumns for imporve filter IOS

---

CHANGELOG.md
ios/Resources/PrivacyInfo.xcprivacy
ios/photo_manager.podspec

feat: add privacy for iOS/macOS

---

example_ohos/ohos/entry/oh-package.json5
example_ohos/ohos/entry/src/main/ets/plugins/GeneratedPluginRegistrant.ets
ohos/photo_manager/src/main/ets/components/plugin/handlers/AlbumHandler.ets
ohos/photo_manager/src/main/ets/components/plugin/handlers/PermissionHandler.ets
ohos/photo_manager/src/main/ets/components/plugin/handlers/PhotoAssetHandler.ets
ohos/photo_manager/src/main/ets/components/plugin/handlers/SaveHandler.ets

1. update openSetting (OpenHarmony) 
2. add fulll error info (OpenHarmony) 
3. update save api (OpenHarmony)

  update openSetting , add fulll error info,update save api  for OpenHarmony

---

.github/workflows/runnable.yml

CI: upload apk in PR

---

.github/workflows/runnable.yml

CI: Just upload apk in pull request

---

ios/Resources/PrivacyInfo.xcprivacy

https://github.com/fluttercandies/flutter_photo_manager/issues/1112#issuecomment-2089480838

🔧 Declare `NSPrivacyAccessedAPICategoryFileTimestamp`

---

CHANGELOG.md
android/build.gradle

fix: Modified the way to read the Java version in build.gradle.

---

CHANGELOG.md
example/lib/model/photo_provider.dart
example/lib/page/developer/develop_index_page.dart
example/lib/page/developer/verbose_log_page.dart
example/lib/util/log_export.dart
lib/src/internal/plugin.dart
lib/src/managers/photo_manager.dart

dev: add log for plugin channel

---

android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionDelegate.kt

For issue [1176](https://github.com/fluttercandies/flutter_photo_manager/issues/1176)

fix: compile error on Android 15 (SDK 35).

---

CHANGELOG.md
ios/Classes/core/PMManager.m

🐛 Reuse file when saving image on Darwin

---

README.md
lib/src/types/entity.dart

You can "be cautious", but when talking about using something it's "with caution".

docs: fix typo in comment

---

.github/workflows/runnable.yml
example/android/.gitignore
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
example/pubspec.lock
lib/src/filter/custom/advance.dart
lib/src/internal/plugin.dart
lib/src/managers/notify_manager.dart
lib/src/types/entity.dart
lib/src/utils/column_utils.dart

- Update Gradle version to 8.13 in `example/android/gradle/wrapper/gradle-wrapper.properties`
- Update Gradle plugins in `example/android/settings.gradle`
- Update compileSdkVersion to 35 in `example/android/app/build.gradle` and `example/android/build.gradle`
- Migrate plugins block in `example/android/app/build.gradle`
- Update photo_manager version to 3.6.4 in `example/pubspec.lock`
- Add `.kotlin` to `.gitignore`
- Update Kotlin version
feat: 更新 Android 示例的 Gradle 和依赖项
- 在 `example/android/gradle/wrapper/gradle-wrapper.properties` 中将 Gradle 版本更新至 8.13
- 更新 `example/android/settings.gradle` 中的 Gradle 插件
- 在 `example/android/app/build.gradle` 和 `example/android/build.gradle` 中将 compileSdkVersion 更新至 35
- 迁移 `example/android/app/build.gradle` 中的插件块
- 在 `example/pubspec.lock` 中将 …

feat: Update Gradle and dependencies for Android example

---

.github/workflows/build-example-apk.yml
.github/workflows/check-compatibility.yml
.github/workflows/runnable.yml
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle.properties
example/android/settings.gradle
example/pubspec.lock

🐛 Fix miscellaneous configuration regarding the Android module

---

CHANGELOG.md
README-ZH.md
README.md

CHANGELOG and README
docs for #1288

docs: CHANGELOG and README of includeHiddenAssets

---

CHANGELOG.md
android/build.gradle
pubspec.yaml

`jvmTarget` update
