fluttercandies/flutter_photo_manager

CHANGELOG.md
android/.classpath
android/.project
android/.settings/org.eclipse.buildship.core.prefs
android/build.gradle
android/gradle.properties
android/src/main/kotlin/top/kikt/imagescanner/PermissionsUtils.java
android/src/main/kotlin/top/kikt/imagescanner/thumb/CustomTarget.java
example/android/.project
example/android/.settings/org.eclipse.buildship.core.prefs
example/android/app/.classpath
example/android/app/.project
example/android/app/.settings/org.eclipse.buildship.core.prefs
lib/photo_manager.dart
pubspec.yaml

* Support Android X. 
* Breaking change. Migrate from the deprecated original Android Support Library to AndroidX. This shouldn't result in any functional changes, but it requires any Android apps using this plugin to also migrate if they're using the original support library.

Migrating to AndroidX

---

lib/src/entity.dart

It avoids the error: The method '_mulFromInteger' was called on null.
Here I explain my case: https://github.com/CaiJingLong/flutter_photo/issues/66

Fix null duration

---

ios/Classes/core/PMManager.m

Don't break the iteration when a non-supported type appears.

Fix for album iteration when a folder exists in the user gallery

---

lib/src/entity.dart

Audio and other types asset should return `null` result for the thumbnail.

Prevent audio asset thumbnail load.

---

lib/src/manager.dart

While displaying a gallery with a large list of photos, this line floods the logs. Kindly remove if unnecessary. Thanks.

Remove undesired verbose log

---

android/src/main/kotlin/top/kikt/imagescanner/core/cache/AndroidQCache.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt

- Optimized `getUri(assetId,type, isOrigin)`
- Use the unified `AndroidQDBUtils.getUri(assetId,type, isOrigin)` method
- `DBUtils.getMediaUri(context, id, type)` references `AndroidQDBUtils.getMediaUri(context, id, type)`
- The above modification local test passed

Optimize Uri acquisition based on #341

---

ios/Classes/core/PMManager.m

Make sure `collection` is a `PHAssetCollection` before calling
`fetchKeyAssetsInAssetCollection` with it to prevent crashes. This
check is pretty much the same as is the one in `injectAssetPathIntoArray`.

#395 Fix crash in `logCollections`

---

lib/src/manager.dart

I noticed that my Assets lack `relativePath` (added in #272) when I create them by id and then call `.refreshProperties()`
It looks like `.refreshProperties()` lacks some other properties, like `.orientation`
But as I see, `refreshAssetProperties` (at line 272 in `lib/src/manager.dart` literally copies every property manually. Can't we just.. copy whole object and return it instead?

Add refreshing relative path in Asset.refreshProperties()

---

lib/src/manager.dart
lib/src/utils/convert_utils.dart

AssetEntity#isFavorite is currently returning `null` because it's never being set in dart. This PR should fix that issue.

Include isFavorite attribute into AssetEntity

---

CHANGELOG.md
example/lib/page/image_list_page.dart
lib/src/thumb_option.dart
pubspec.yaml

The issue: 
```dart
testThumbSize(AssetEntity entity, List<int> list) async {
for (final size in list) {
final data = await entity.thumbDataWithSize(
size,
size,
);
if (data == null) {
return;
}
ui.decodeImageFromList(data, (result) {
print(
'size:$size length:${data.length}, size: ${result.width}x${result.height}');
});
}
}
```
The method will return error size thumb on iOS.
---
The pull request will fix it.

Fix thumb option with size

---

ios/Classes/core/PMManager.m

1. Fix fetchFullSizeVideo flow logic. Avoid keeping call fetchFullSizeVideo when progress is 1.0. This operation cause a loop and return ile path before export session process done. 
2. Change requestAVAssetForVideo to requestExportSessionForVideo. Avoid iCloud file export failure. Ref: https://github.com/banchichen/TZImagePickerController/issues/1073 
3. Add modification date as file name prefix. Avoid to get the cache file if user modified the video.

fetchFullSizeVideo will cause a loop and return file path before export session process done.

---

ios/Classes/core/PMManager.m

Reverts CaiJingLong/flutter_photo_manager#478
Not compatible with macOS.
Related #484 .

Revert "fetchFullSizeVideo will cause a loop and return file path before export session process done."

---

ios/Classes/core/PMManager.m

See #455 
Creation instance of`PHCachingImageManager` initiate request permissions dialog. I made cachingManager lazy to fix it. So now permissions won't be asked on application launch, but only when they really needed.

Fixed: permissions dialog on launch on old iOS versions.

---

android/src/main/kotlin/top/kikt/imagescanner/ImageScannerPlugin.kt

Fix #355 .
* Remove deprecated `registerWith`.
* Release plugin instance when detached from the engine.
* Extract the add listener's method.

Add request permissions result listener when activity re-attached

---

lib/src/entity.dart

Continued from #360, fix #531 .
Some other properties still missing, but they are enough to create a `AssetPathEntity`.

Fix `AssetPathEntity.fromId`

---

lib/src/plugin.dart

Some devices will be affected if the extension is missing, which will cause the image failed to save.

Fix `saveImage` method missing file extension for the fallback title

---

ios/Classes/PMPlugin.m

This pull request intends to fix the root cause of the #531 , that the methods related to the `AssetPathEntity` is not working when the permission is limited, not fully authorized.

Limit `AssetPathEntity` methods when the permission is not fully authorized

---

ios/Classes/core/PMManager.m

#558 removed the same calls for video
Seems like those calls lock thread and hang photo loading
Issues:
https://github.com/CaiJingLong/flutter_photo_manager/issues/411
https://github.com/CaiJingLong/flutter_photo_manager/issues/377
https://github.com/CaiJingLong/flutter_photo_manager/issues/308
https://github.com/CaiJingLong/flutter_photo_manager/issues/420

iCloud photos fetch fix

---

ios/Classes/core/PMManager.m

`isAll` is not set correctly when using the `fetchPathProperties` method.

🐛 `fetchPathProperties` returned wrong `isAll` on iOS

---

ios/Classes/core/PMManager.m

1. Fix sync photos between mac and ios, but PhotoManager.getAssetPathList can't fetch "from my mac" problem.
2. Fix user add a album in a new folder, but PhotoManager.getAssetPathList can't fetch this albem problem.
- 修正使用者從mac同步至ios後，ios會產生一個from my mac及相簿，但PhotoManager.getAssetPathList無法取得該相簿問題。
- ios照片內新增資料夾及相簿，但PhotoManager.getAssetPathList無法取得該資料夾內相簿問題。

Fix list all album on iOS

---

lib/src/entity.dart
lib/src/filter/filter_options.dart
lib/src/manager.dart

Removed APIs:
- `AssetEntity.fullData`
- `FilterOptionGroup.dateTimeCond`
- `PhotoManager.getImageAsset`
- `PhotoManager.getVideoAsset`
- `PhotoManager._getFullDataWithId`
Deprecated APIs:
- `AssetPathEntity.assetList`
- `PhotoManager.requestPermission`
Also improve some comments.

🔥 Apply more deprecations

---

ios/Classes/core/PMManager.m

Currently, iCloud Shared Albums are filtered out of the results because Apple returns them as type 
`PHCloudSharedAlbum`, which is inherited from `PHAssetCollection`, but it only allows for exact match of `PHAssetCollection`. This change ensures those albums are returned correctly. 
This should fix #521

Include iCloud Shared Albums in the gallery list

---

.github/workflows/build_test.yml
example/lib/page/image_list_page.dart
lib/src/types/types.dart
pubspec.yaml
test/photo_manager_test.dart

🎨 Override `RequestType`'s equality

---

android/src/main/kotlin/com/fluttercandies/photo_manager/thumb/ThumbnailUtil.kt

Glide will now run on the background thread.
Fix #649, #587.
(I'm not sure if it's truly running on another thread, but it's under the thread pool.)

⚡️ Run Glide on current thread

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt
ios/Classes/core/PMFilterOption.m
ios/Classes/core/PMManager.m
lib/src/filter/filter_option_group.dart
lib/src/filter/filter_options.dart

- Flutter: Remove the default `OrderOption` when constructing the group.
- Android: Use `MediaStore.MediaColumns._ID` with descending by default.
- iOS: Use `nil` sort descriptors and reverse the asset array.
- Suggested by the [answer](https://stackoverflow.com/a/29949179).
Related to #655, #603.
- Users won't able to trigger the default sort order manually, only if they pass an empty list of orders.
- Platform handlers are quite separate here, but I left comments, and let's hope it worked.

🎨 Improve platform default sort orders

---

example/lib/model/photo_provider.dart
example/lib/page/home_page.dart
ios/Classes/PMPlugin.m
ios/Classes/core/PMAssetPathEntity.h
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMFilterOption.h
ios/Classes/core/PMFilterOption.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/filter/filter_option_group.dart
lib/src/managers/photo_manager.dart
lib/src/types/entity.dart
lib/src/utils/convert_utils.dart

Resolves #386.
This PR also introduced a behavior breaking change:
`containsLivePhotos` are `true` by default. If you previously used `RequestType.video` to filter assets, they'll include live photos now. To keep to old behavior, you should explicitly set `containsLivePhotos` to `false` in this case.

✨ Support filtering Live Photos

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/Android30DbUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
example/lib/model/photo_provider.dart
ios/Classes/PMPlugin.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/internal/plugin.dart
lib/src/managers/photo_manager.dart
lib/src/types/entity.dart
lib/src/utils/convert_utils.dart

- Arguments with `getAssetListPaged` are now required with name.
- `AssetPathEntity` cannot be constructed with the default constructor.
- `PhotoManager.notifyingOfChange` has no setter anymore.
- `PhotoManager.refreshAssetProperties` and `PhotoManager.fetchPathProperties` have been moved to entities.

🎨 Unify codes

---

android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
example/android/app/src/main/AndroidManifest.xml

Resolves #665, #470.
`WRITE_EXTERNAL_STORAGE` and `ACCESS_MEDIA_LOCATION` are removed from the plugin's manifest and will request to for granted accordingly.

🔥 Request `WRITE_EXTERNAL_STORAGE` only when needed

---

ios/Classes/core/PHAsset+PHAsset_getTitle.m
ios/Classes/core/PMManager.m

Resolves #678, might be related to #636.
Files will be cached into the sandbox, but not matched with the modified date, which causes the same file returned without checking the modified date.

⚡️ [iOS] Improve cache path for `PHAsset`

---

MIGRATION_GUIDE.md
example/lib/model/photo_provider.dart
example/lib/widget/gallery_item_widget.dart
lib/src/internal/editor.dart
lib/src/internal/plugin.dart
lib/src/types/entity.dart
lib/src/utils/convert_utils.dart

Breaking changes:
- `AssetPathEntity` and `AssetEntity` become immutable.
- `IosEditor.favoriteAsset` now returns `AssetEntity?` instead of boolean value.
- `AssetPathEntity.refreshPathProperties` has been removed, use `obtainForNewProperties` with different signature.
- `createDtSecond` has been renamed to `createDateSecond` in `AssetEntity`.
- `refreshProperties` has been renamed to `obtainForNewProperties` in `AssetEntity`.

⚡️ Make all entities immutable

---

example/lib/util/common_util.dart
ios/Classes/PMPlugin.m
ios/Classes/core/PHAsset+PM_COMMON.h
ios/Classes/core/PHAsset+PM_COMMON.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/internal/constants.dart
lib/src/internal/plugin.dart
lib/src/types/entity.dart

On iOS, we can detecting MIME type from UTI.
See https://developer.apple.com/documentation/photokit/phassetresource/1623989-uniformtypeidentifier?language=objc and https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-SW1

Support 'mimeType' for iOS and macOS

---

ios/Classes/core/PHAssetCollection+PM_COMMON.m
ios/Classes/core/PMManager.m

`estimatedAssetCount` will produce an unreliable count of assets. In our case, when we're requesting audios on iOS, it gave **2** instead of **0**, which broke further behaviors that integrate with assets.

🔥 [iOS] Remove estimated asset count obtain

---

android/src/main/kotlin/com/fluttercandies/photo_manager/constant/AssetType.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/constant/Methods.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/AssetType.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/entity/FilterOption.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionsUtils.kt
example/android/app/src/main/AndroidManifest.xml

Fix #722.
This fixes methods related to the `WRITE_EXTERNAL_STORAGE` permission on Android versions that are below 29. All methods are predefined, permissions requirements are checked based on each call's method.

🚑️ [Android] Predicate more precise permissions requirements

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/thumb/ThumbnailUtil.kt

Further improvements for #727, #707.
Now the plugin will obtain thumbnails and `originBytes` using the Content URI as much as possible, to avoid some storage mechanisms with various vendors.

⚡️ [Android] Using `ContentResolver` as much as possible

---

lib/src/internal/image_provider.dart

Solves the coming lint issues with Flutter 2.13, and keeps the compatibility of previous Flutter versions.

🚨 Ignore null-aware operator for `PaintingBinding`'s instance

---

CHANGELOG.md
ios/Classes/core/PMManager.m

Use `NOT` instead of `!=` in live-photo filtering expression.
With original predicate, a lot of non-live-photo cannot bet fetched unexpectedly.

[iOS] Predicate for live-photo filtering workaround

---

CHANGELOG.md
example/pubspec.yaml
lib/src/internal/plugin.dart
pubspec.yaml

🐛 Fix invalid type cast with `AssetEntity.exists`

---

CHANGELOG.md
example/lib/main.dart
example/lib/model/photo_provider.dart
example/lib/page/developer/dev_title_page.dart
example/lib/page/developer/issues_page/issue_734.dart
example/lib/page/home_page.dart
example/lib/page/image_list_page.dart
example/lib/widget/gallery_item_widget.dart
example/pubspec.yaml
ios/Classes/PMPlugin.m
ios/Classes/core/PHAsset+PM_COMMON.m
ios/Classes/core/PHAssetCollection+PM_COMMON.m
ios/Classes/core/PMAssetPathEntity.h
ios/Classes/core/PMAssetPathEntity.m
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMFilterOption.h
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/filter/filter_option_group.dart
lib/src/internal/constants.dart
lib/src/internal/plugin.dart
lib/src/types/entity.dart
lib/src/utils/convert_utils.dart
pubspec.yaml

- Deprecate `AssetPathEntity.assetCount`.
- Add `AssetPathEntity.assetCountAsync`.
- Remove `containsEmptyAlbum` from `FilterOptionGroup`.
Before:
After:

✨ `AssetPathEntity.assetCountAsync`

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
pubspec.yaml

🐛 [Android] Use `RELATIVE_PATH` only on Android Q+

---

CHANGELOG.md
ios/Classes/core/PMManager.m
pubspec.yaml

🐛 [iOS] Avoid duplicate `copyItemAtURL`

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/constant/Methods.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionsUtils.kt
pubspec.yaml

- Do not require `READ_EXTERNAL_STORAGE` on Android 33.
- Explicitly handle `requestPermissionExtend` with Android 33 permissions.

🐛 [Android] Correct permission checks with `requestPermissionExtend` on Android 33

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt

Fix #867 
- Saving now gets rid of `FileOutputStream`
- Throws more `RuntimeException` with if failed to invoke with the Content Provider
- `IDBUtils.exists` -> `IDBUtils.assetExists`

⚡️ [Android] Combine saving methods into `IDBUtils`

---

CHANGELOG.md
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionsUtils.kt

Although the document says *starting in API level 33, this permission has no effect*, we still heard from many users that devices are unable to fetch assets. From the comment https://github.com/fluttercandies/flutter_photo_manager/issues/852#issuecomment-1296844804 the permission might affect the result. So until the permission is deprecated, we might continue to declare the permission as well.
Related issues:
- https://github.com/fluttercandies/flutter_photo_manager/issues/852
- https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/388

⚡️ [Android] Always declare `READ_EXTERNAL_STORAGE` on Android

---

lib/src/types/entity.dart

AssetPathEntity constructor now takes `PMFilter` class as a result of the new custom filter feature.
This fixes `copyWith` accordingly.

fix: fix asset path entity copyWith to also allow custom filter

---

CHANGELOG.md
lib/src/filter/path_filter.dart

Fixes compile on Web. https://github.com/fluttercandies/flutter_photo_manager/pull/950#issuecomment-1660173426.

`.pow(2^63)-1` instead of `9223372036854775807`

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt

App crashes when photo_manager tries to request a cache thumbnail for a broken image file, like this one:
https://drive.google.com/file/d/1-8C4w2fhbHh2EmsJPF2SN0de3NiTNiCN/view?usp=drivesdk
Catch the thrown exception so that the main app does not crash.

Try catch request cache thumbnail

---

CHANGELOG.md
lib/src/internal/image_provider.dart
pubspec.yaml

Resolves https://github.com/LeGoffMael/insta_assets_picker/issues/24.

✨ Add locks to the image provider

---

CHANGELOG.md
ios/Classes/core/PHAsset+PM_COMMON.h
ios/Classes/core/PHAsset+PM_COMMON.m

- Add method **_getUntouchedResource_** to retrieve original photo/video instead of altered one (with adjustments / filters)
- **Fix**: When retrieving an asset title ( with _entity.title_ or _entity.titleAsync_) now returns original file name instead of '**_FullSizeRender.*_**' if this has adjustments.
Related Issues:
Fixes #976
Fixes https://github.com/immich-app/immich/issues/4088

[IOS] FIX: Return original filename instead of FullSizeRender

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerDeleteManager.kt

The current implementation of trashing the asset instead of deleting it in Android 30 and above feels inconsistent with the rest of the behavior of the API in older versions of Android and iOS where the asset is irrevocably deleted.
It is changed in this PR to have the same behavior of deleting the asset using `MediaStore.createDeleteRequest` which based on the [documentation](https://developer.android.com/reference/android/provider/MediaStore#createDeleteRequest(android.content.ContentResolver,%20java.util.Collection%3Candroid.net.Uri%3E)) calls [ContentResolver#delete](https://developer.android.com/reference/android/content/ContentResolver#delete(android.net.Uri,%20android.os.Bundle)) similar to the [handling](https://github.com/fluttercandies/flutter_photo_manager/blob/ba688606fddaa910b …

fix: delete assets permanently deleted instead of trash in android R

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerDeleteManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
example/lib/page/developer/issues_page/issue_988.dart
example/lib/widget/nav_column.dart
pubspec.yaml

- Fix `PhotoManager.editor.deleteWithIds` method not working on Android API 29.
- Upgrade pubspec version

fix: `deleteWithIds` method not working

---

.github/workflows/runnable.yml
example/lib/page/custom_filter/custom_filter_sql_gif_image.dart

Because someone reported that building Android on windows/macOS will report an error, I tried to add CI to try whether the packaging on windows and macOS can be successful.

CI: Add build apk android on win/mac

---

ios/Classes/core/PMManager.m

One of my videos can't generate a thumbnail and it causes the error `Domain=PHPhotosErrorDomain Code=3303`, resulting in `fetchThumb` never calling back.
We should handle this case probably the same way as when `imageData` is `nil`.
I'm attaching the video I have issue with.
https://github.com/fluttercandies/flutter_photo_manager/assets/11507974/b2d3d444-072a-4e50-8060-ef61e172fe88

[iOS] Handle error when fetching thumbnail

---

CHANGELOG.md
example/pubspec.yaml
ios/Classes/core/PHAssetResource+PM_COMMON.m
pubspec.yaml

Fixes #1151. Fixes compile exceptions with Xcode versions that are not compatible with iOS 17.0.

🐛 [iOS] Add `__IPHONE_17_0` pragma

---

CHANGELOG.md
MIGRATION_GUIDE.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManager.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerPlugin.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/entity/AssetEntity.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/CommonExt.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
example/lib/page/developer/develop_index_page.dart
example/lib/page/save_image_example.dart
ios/Classes/PMPlugin.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
lib/src/internal/editor.dart
lib/src/internal/plugin.dart

The request reorg all input streams after each of its usages. This likely solves the EXIF problem that occasionally happens on devices, such as invalid orientation values. Also, to help with the `saveImage` success rate on Android, the `title` parameter has been changed to `filename`.

⚡️ Reorg input streams when saving asset on Android

---

README-ZH.md

docs: fix flutter issue link

---

CHANGELOG.md
example/lib/page/image_list_page.dart
ios/Classes/core/PMManager.m

When the video resource is read for the first time, it will fetch the resource and write corresponding files. But if the file type is specified, the previous code does not make an exportation but uses copying only, which results in incorrect video files.
The request fixes the issue, it also raises an error when the exported file's extension does not match with the target.

🐛 Fix export session file type with videos at the first time

---

android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoManagerDeleteManager.kt

When the file is created by the application itself, the uri can be deleted successfully without causing a RecoverableSecurityException.
[Note]: I tried Android 13 and the same way can also delete files created by the application without triggering the dialog. Maybe developers can decide in the future whether to force the use of createDeleteRequest method. (optional)

🐛 Fix no returned ids after successful deletion on Android API 29+

---

android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate34.kt

mediaLocation = true does not work when the app already has common permissions on Android API 34

🐛 Fix mediaLocation = true does not work on Android API 34

---

CHANGELOG.md
example/pubspec.yaml
example_ohos/pubspec.yaml
ios/Classes/PMPlugin.m
ios/Classes/core/PMManager.h
ios/Classes/core/PMManager.m
pubspec.yaml

To avoid crashes on specific Xcode versions, typically Xcode 15.0.x.
Fixes https://github.com/fluttercandies/flutter_photo_manager/issues/1208

🔥 Get rid of try catch when toggling favorite on Darwin

---

CHANGELOG.md
example/ios/Runner/AppDelegate.swift
ios/Classes/core/PMManager.m

Fixes https://github.com/fluttercandies/flutter_photo_manager/issues/1196

🐛 Do not use `privateFileURL` on iOS 18+

---

CHANGELOG.md
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
lib/src/internal/plugin.dart
lib/src/types/entity.dart
pubspec.yaml

🐛 Do not throw when querying not existing assets in bulk on Android

---

.github/workflows/issue-triage.yml

Repo: https://github.com/fluttercandies/triage_bot_for_flutter_photo_manager/tree/main/pkgs/issue_triage_bot

CI: Issue Triage Bot

---

CHANGELOG.md
README-ZH.md
README.md
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate19.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate23.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate33.kt
android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate34.kt
pubspec.yaml

`READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` are both required whether requesting images or videos.

🐛 Fix request permissions for images and videos on Android API 33+

---

CHANGELOG.md
example/lib/page/developer/issues_page/issue_1271_demo.dart
example/lib/page/developer/issues_page/issue_index_page.dart
example/macos/Runner/AppDelegate.swift
example/pubspec.lock
example/pubspec.yaml
ios/Classes/core/PMThumbLoadOption.m
lib/src/types/entity.dart

- Fix inconsistent resizing behavior between iOS and Android in `thumbnailDataWithSize`. (#1271) (修复 `thumbnailDataWithSize` 在 iOS 和 Android 上的尺寸调整行为不一致的问题)
- Add a demo page `issue_1271_demo.dart` to reproduce the issue (添加一个 demo 页面 `issue_1271_demo.dart` 来复现此问题)
- Modify the default value to `PHImageContentModeAspectFill` in `PMThumbLoadOption.m` to align iOS behavior with Android (在 `PMThumbLoadOption.m` 中修改默认值为 `PHImageContentModeAspectFill`，使 iOS 行为与 Android 一致)
- Set `resizeContentMode: ResizeContentMode.fill` in `AssetEntity.dart` (在 `AssetEntity.dart` 中设置 `resizeContentMode: ResizeContentMode.fill`)
- Upgrade `image` version to `4.5.4` (升级 `image` 版本到 `4.5.4`)
- Fix `example/macos/Runner/AppDelegate.swift` to use `@main` (修复 `example/macos/Runner/AppDelegate.swift` 使用 `@main`)

fix: Fix inconsistent thumbnail resizing on iOS (修复 iOS 缩略图尺寸不一致)

---

example/lib/model/photo_provider.dart
example/lib/page/custom_filter/include_hidden_test_page.dart
example/lib/page/custom_filter_example_page.dart
example/lib/page/filter_option_page.dart
example/lib/page/home_page.dart
ios/Classes/core/PMConvertUtils.m
ios/Classes/core/PMFilterOption.h
ios/Classes/core/PMFilterOption.m
lib/src/filter/base_filter.dart
lib/src/filter/classical/filter_option_group.dart

- Add `includeHiddenAssets` property to `FilterOptionGroup` and `PMFilter` classes. (在 `FilterOptionGroup` 和 `PMFilter` 类中添加 `includeHiddenAssets` 属性。)
- Add `includeHiddenAssets` checkbox to `FilterOptionPage` to control the visibility of hidden assets on iOS. (在 `FilterOptionPage` 中添加 `includeHiddenAssets` 复选框，用于控制 iOS 上隐藏资源的可见性。)
- Create `IncludeHiddenTestPage` to test the count of hidden and non-hidden assets. (创建 `IncludeHiddenTestPage` 页面，用于测试 隐藏和非隐藏资源的计数。)
- Modify `PMConvertUtils.m` and `PMFilterOption.m` to handle the `includeHiddenAssets` option on iOS. (修改 `PMConvertUtils.m` 和 `PMFilterOption.m` 以处理 iOS 上的 `includeHiddenAssets` 选项。)
- Update example app to include the new test page in `CustomFilterExamplePage`. (更新示例应用程序，在 `CustomFilterExamplePage` 中包含新的测试页面。)

feat: Add includeHiddenAssets option (新增包含隐藏资源选项)
